### ISSUE TITLE
Install fails - 'Promise is not defined'

### ISSUE THREAD

**Issue by mhaeberli** [gladwinbobby/bitbucket-repository-downloader#1]
Looks very cool and useful.
But Install fails:
`/home/<redacted>/bitbucket-repository-downloader/node_modules/nodegit/utils/execPromise.js:7
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at module.exports (/home/<redacted>/bitbucket-repository-downloader/node_modules/nodegit/utils/execPromise.js:7:14)
    at Module.prepareForBuild [as exports] (/home/<redacted>/bitbucket-repository-downloader/node_modules/nodegit/lifecycleScripts/preinstall.js:11:10)
    at Object.<anonymous> (/home/<redacted>/bitbucket-repository-downloader/node_modules/nodegit/lifecycleScripts/preinstall.js:37:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3`

please advise ...

**Comment by gladwinbobby** [comment]
Thanks for trying this repo. I guess you are using an old version of NodeJS. Please make sure you are using the latest LTS version. This issue is addressed here. [https://github.com/nodegit/nodegit/issues/1118](url)

**Comment by mhaeberli** [comment]
thx
