### ISSUE TITLE
undefined:1 SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Blood13** [gladwinbobby/bitbucket-repository-downloader#18]
Hello!
I want to say thank you. Your tool really helped me last year. 
Today I had tried to do backup and ran into a problem.
This is how it looked like:
```
node clone.js --username=xxxx --password=xxxx
Loading all repositories.. please wait..
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/root/backup/bitbucket-repository-downloader/clone.js:76:23)
    at Request.self.callback (/root/backup/bitbucket-repository-downloader/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/root/backup/bitbucket-repository-downloader/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/root/backup/bitbucket-repository-downloader/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
```

**Comment by gladwinbobby** [comment]
I believe bitbucket's APIs have changed. I'll have a look into it this weekend.
